#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Allow traffic on port 80
ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo /var/www/html/index.html

# test and restart nginx
nginx -t
service nginx restart
