#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx configurations
sudo nginx -t
sudo service nginx reload
