#!/usr/bin/env bash
# 404 page

apt-get update
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/kariukikinyanjui permanent;"

sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-available/default

# creating 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sed -i "s/listen 80 default_server;/$replacement_string/" /etc/nginx/sites-available/default

# custom http header
sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# test and restart nginx
nginx -t
service nginx restart
