#!/usr/bin/env bash
# Configure Nginx on web-01 and web-02
apt-get update
apt-get -y nginx

# create index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a redirection
replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/kariukikinyanjui permanent;"

sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-available/default

# Custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom http header
sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# test for syntax error and restart nginx
nginx -t
service nginx restart
