#!/usr/bin/env bash
# Install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo service haproxy start

lb1="listen lb"
lb2="bind 0.0.0.0:80"
lb3="mode http"
lb4="balance roundrobin"
lb5="option httpclose"
lb6="option forwardfor"
lb7="server 327513-web-01 54.85.169.159:80 check"
lb8="server 327513-web-02 54.210.87.169:80 check"
haproxy_default="/etc/default/haproxy"
haproxy_cfg_file="/etc/haproxy/haproxy.cfg"
s="\n\t"; e="\n";
load_balancer_cfg="${lb1}${s}${lb2}${s}${lb3}${s}${lb4}${s}${lb5}${s}${lb6}${s}${lb7}${s}${lb8}${e}"

## Set managable via inet script
sudo sed -i "\$a ENABLED=1" "${haproxy_default}"

## Append config setup
sudo sed -i "\$a ${load_balancer_cfg}" "${haproxy_cfg_file}"

printf %s "global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend http-in
  timeout client 50000
  bind 0:80
  default_backend servers

backend servers
  timeout connect 5000
  timeout server 50000
  balance roundrobin
  server 327513-web-01 54.85.169.159 check
  server 327513-web-02 54.210.87.169 check
">> /etc/haproxy/haproxy.cfg
service haproxy restart
