#!/usr/bin/env bash
# Displays a message indefinitely with a sleep 2 in between each iteration.
# Displays a different message between each iteration.

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
