#!/usr/bin/env bash
# Initialize a counter
counter=1

# Iterate from 1 to 10 using a while loop
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
